# -*- mode: ruby -*-
# vi: set ft=ruby :
#$script = <<SCRIPT
#yum -y install cloud-init
#SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/impish64"
  config.vm.hostname = "shu-ubun.local"
  config.vm.network "public_network", ip: "192.168.11.85", bridge: "Realtek PCIe GbE Family Controller"
  config.vm.provision "shell",
    run: "always",
    inline: "ip route add default via 192.168.11.1"
  config.vm.provision "shell",
    run: "always",
    inline: "ip route del default via 10.0.2.2"
  #Install Cloud-init
  #config.vm.provision "shell", inline: $script

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
  end
  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.name = "shu-ubun"
    v.memory = 2048
    v.cpus = 2
  end
  config.disksize.size = '50GB'

  # Deploy Public Key
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/key.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      # echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
  end

end
